config/routes.rb
Rails.application.routes.draw do
  root 'retro_items#index'

  resources :retro_items
end

app/models/retro_item.rb
class RetroItem < ActiveRecord::Base
  enum happiness: ['happy', 'meh', 'sad']

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/retro_items_controller.rb
class RetroItemsController < ApplicationController
  def index
    @retro_items = RetroItem.order('happiness').all

    render :index, status: 200
  end

  def new
    @retro_item = RetroItem.new
    @statuses = RetroItem.happinesses.keys.to_a
  end

  def create
    if RetroItem.create!(retro_params)
      flash[:success] = 'Retro Item added'
      redirect_to '/'
    else
      flash[:alert] = 'Unable to create new retro item'
    end
  end

  def edit
    @retro_item = RetroItem.find_by(id: params[:id])
    @statuses = RetroItem.happinesses.keys.to_a
  end

  def update
    if RetroItem.find_by(id: params[:id]).update_attributes!(retro_params)
      flash[:success] = 'Retro Item Updated'
    else
      flash[:alert] = 'Unable to update retro item'
    end

    redirect_to '/'
  end
  
  def destroy
    RetroItem.find_by(id: params[:id]).destroy
    flash[:success] = 'Retro Item Deleted'
 
   redirect_to retro_items_url 
  end

  private

  def retro_params
    params.require(:retro_item).permit(:description, :happiness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/

    %title= content_for?(:title) ? "Gazebo - #{content_for(:title)}" : "Gazebo"
    
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
  %header
    .gazebo.title Gazebo!
    .gazebo.sub-title Where to gather and share ideas
  #content
    = yield

app/views/retro_items/edit.html.haml
= form_for(@retro_item) do |f|
  = f.label :description
  = f.text_area :description
  = f.label :happiness
  = f.select :happiness, @statuses
  = f.submit 'Update Retro Item'
  %a= link_to 'Delete Retro Item', @retro_item, method: :delete, confirm: 'Positive about deleting?' 
  %a= link_to 'Cancel', retro_items_path

app/views/retro_items/index.html.haml
= content_for(:title) { 'Current Retro Items' } 
%h1 Current Retro Items
%a= link_to 'Add New Retro Item', new_retro_item_path

#retro-items-list
  - @retro_items.each do |retro_item|
    .retro-item(class="#{retro_item.happiness}")
      %a= link_to retro_item.description, edit_retro_item_path(retro_item)

app/views/retro_items/new.html.haml
= form_for @retro_item do |f|
  = f.label :description
  = f.text_area :description

  = f.label :happiness
  = f.select :happiness, @statuses

  = f.submit 'Add Retro Item'
%a= link_to 'Cancel', retro_items_path